name: Build and Push Image

on:
  push:
    branches:
      - main

env:
  REGISTRY: registry.jiun.dev
  IMAGE_NAME: claude-code-cloud

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITEA_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ gitea.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max

      - name: Update image tag in kustomization.yaml
        run: |
          cd kubernetes
          sed -i "s/newTag: .*/newTag: ${{ gitea.sha }}/" kustomization.yaml
          cat kustomization.yaml

      - name: Commit and push updated manifest
        run: |
          git config user.name "Gitea Actions"
          git config user.email "actions@gitea.jiun.dev"
          git add kubernetes/kustomization.yaml
          git diff --staged --quiet || git commit -m "chore: update image tag to ${{ gitea.sha }}"
          git push
