name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

env:
  INTERNAL_REGISTRY: registry.internal.jiun.dev
  PUBLIC_REGISTRY: registry.jiun.dev
  IMAGE_NAME: claude-code-cloud

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host
          config-inline: |
            [registry."registry.internal.jiun.dev"]
              http = true
              insecure = true

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.INTERNAL_REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.INTERNAL_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.INTERNAL_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ gitea.sha }}
          cache-from: type=registry,ref=${{ env.INTERNAL_REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.INTERNAL_REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max

      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy to Kubernetes
        run: |
          cd ${{ gitea.workspace }}/kubernetes
          kustomize edit set image ${{ env.PUBLIC_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ gitea.sha }}
          kubectl apply -k . --namespace=claude-code-cloud
          kubectl rollout status deployment/claude-code-cloud -n claude-code-cloud --timeout=300s

      - name: Verify deployment
        run: |
          kubectl get pods -n claude-code-cloud -l app=claude-code-cloud
          kubectl get svc -n claude-code-cloud
